### ISSUE TITLE
handlers[message.type] is not a function

### ISSUE THREAD

**Issue by BobbyWibowo** [CT1994/gulp-multi-thread-task#4]
Any idea why these happens?
```
$ npx gulp lint:js2
[04:23:20] Using gulpfile ~/src/projectName/gulpfile.js
[04:23:20] Starting 'lint:js2'...
[04:23:20] spawning 4 worker
[04:23:22] Using gulpfile ~/src/projectName/gulpfile.js
[04:23:22] Starting 'lint:js2'...
[04:23:22] 'lint:js2' errored after 2 s
[04:23:22] TypeError: handlers[message.type] is not a function
    at Worker.<anonymous> (/home/bobby/src/projectName/node_modules/gulp-multi-thread-task/index.js:30:29)
    at Worker.emit (events.js:326:22)
    at Worker.EventEmitter.emit (domain.js:506:15)
    at ChildProcess.<anonymous> (internal/cluster/worker.js:32:12)
    at ChildProcess.emit (events.js:314:20)
    at ChildProcess.EventEmitter.emit (domain.js:506:15)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
[04:23:22] Using gulpfile ~/src/projectName/gulpfile.js[04:23:22] Starting 'lint:js2'...
[04:23:22] The following tasks did not complete: lint:js2                                                                                                                 
[04:23:22] Did you forget to signal async completion?
[04:23:22] The following tasks did not complete: lint:js2
[04:23:22] Did you forget to signal async completion?
[04:23:23] Using gulpfile ~/src/projectName/gulpfile.js
[04:23:23] Starting 'lint:js2'...
[04:23:23] 'lint:js2' errored after 3.54 ms
[04:23:23] Error: write EPIPE
    at process.target._send (internal/child_process.js:806:20)
    at process.target.send (internal/child_process.js:677:19)
    at _requestFile (/home/bobby/src/projectName/node_modules/gulp-multi-thread-task/lib/message-handlers.js:75:13)
    at workerMessageHandlers (/home/bobby/src/projectName/node_modules/gulp-multi-thread-task/lib/message-handlers.js:110:3)
    at GulpMultiThreadTask (/home/bobby/src/projectName/node_modules/gulp-multi-thread-task/index.js:77:27)
    at /home/bobby/src/projectName/gulpfile.js:81:10
    at lint:js2 (/home/bobby/src/projectName/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:427:14)
    at runBound (domain.js:440:12)
    at asyncRunner (/home/bobby/src/projectName/node_modules/async-done/index.js:55:18)
```

I believe the `write EPIPE` errors were simply due to the gulp task ending prematurely due to the first `handlers[message.type] is not a function` error.

Here's the snippet of my gulp file:
```js
const gulp = require('gulp')
const { GulpMultiThreadTask } = require('gulp-multi-thread-task')
const eslint = require('gulp-eslint7')
// ...

function lintJs2 (done, src) {
  return gulp.src(src)
    .pipe(eslint())
    .pipe(eslint.format('stylish'))
    .pipe(eslint.failAfterError())
}

gulp.task('lint:js2', function (done, src) {
  return GulpMultiThreadTask(
    'lint:js2',
    [
      './*.js',
      './{scripts,src}/**/*.js'
    ],
    lintJs2,
    {
      concurrency: Math.min(require('os').cpus().length / 2)
    }
  )
})

// ...
```

**Comment by CT1994** [comment]
Thank you for the feedback I will take a look into your report and feedback
